# Reloaded.Community only stores xx3 hash for latest Steam version!
# See https://github.com/Reloaded-Project/Reloaded.Community/blob/main/Apps/Metaphor%20ReFantazio/App.json
# We'll try to provide support for as many versions of the full game as possible
# Hashes are stored in the TOML as strings since the toml crate used doesn't support u64

# Metaphor: Refantazio
XRD759_STEAM_102 = "0x7e8170c685f06713"
XRD759_STEAM_103 = "0x85482f618f556093"
XRD759_STEAM_109 = "0x52537a56edc53f12"
XRD759_STEAM_1011 = "0x39d13fb3fc914659"

XRD759_UWP_102 = "0xc321904755d75405"
XRD759_UWP_103 = "0xccac4e585f26888f"
XRD759_UWP_1011 = "0x51d3b74ca903fd98"

# Persona 3 Reload
XRD777_STEAM_107 = "0x653f6691fa36125b"
XRD777_STEAM_108 = "0x5e5cfd6823c5af57"
XRD777_STEAM_109 = "0x23af0753c22a6dfc"