[package]
name = "riri-mod-tools-proc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"

riri-mod-tools-impl = { path = "../riri-mod-tools-impl" }
